- name: Install RabbitMQ server
  hosts: rabbitmq_all
  user: root
  serial:
    - 1
    - 100%
  roles:
    - role: rabbitmq_server
      tags:
        - rabbitmq-server

  vars:
    rabbitmq_cookie_token: secrete
